name: FaceLiveIOS
options:
  deploymentTarget:
    iOS: "16.0"
  bundleIdPrefix: com.facelive
settings:
  base:
    SWIFT_VERSION: 5.9
packages:
  AmigoFaceSwapSDK:
    url: https://github.com/AmigoAIAdmin/AmigoSDK_iOS.git
    branch: main
targets:
  FaceLiveIOS:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: FaceLiveIOS
        excludes:
          - CameraModel.swift
    info:
      path: FaceLiveIOS/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.facelive.ios
        INFOPLIST_FILE: FaceLiveIOS/Info.plist
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
    dependencies:
      - package: AmigoFaceSwapSDK
